<h1 style="text-align:center;color:white;background-color:#2471A3;padding:10px;border-radius:8px;">Customer Support Ticket Analysis</h1>

### Introduction to Customer Support  Analysis
A **stroke** is a medical condition that occurs when the brain does not receive enough blood flow due to a blockage or bleeding.This sudden interruption stops the supply of oxygen,causing brain cells to get damaged within minutes,leading to lasting brain damage,disability,or death.

The purpose of this analysis is to understand key factors related to stroke and present insights through clear and meaningful data visualization.This project uses Python libraries such as **Pandas**,**Numpy**,**Plotly**,**Matplotlib**,and **Seaborn** to analyze a stroke dataset.

### Imported Required Libraries
All neccessary Python libraries such as Pandas,Numpy,Plotly,Matplotlib,and Seaborn are imported for performing data loading,cleaning,exploration,and visualization.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

<h2 style="
    text-align:center;
    background-color:#eef3ff;
    padding:10px 15px;
    border-radius:5px;
    color:#2c7be5;
    font-size:30px
">
 Data Loading and Initial Overview
</h2>

In [2]:
#Importing the Dataset
df=pd.read_csv("Customer_supoort_tickets1.csv")

***Info:-*** Used Pandas to load the dataset into Python,so that it can be viewed,explored,and prepared for further analysis.

### (ii) Initial Overview of the Dataset

In [3]:
#Displaying the Dimensions of the Dataset
print("Number of Rows:",df.shape[0])
print("Number of Columns:",df.shape[1])

Number of Rows: 999
Number of Columns: 17

***Info:-*** Shows how many rows and columns are present.

In [4]:
#Displaying the First 5 Rows
df.head()

,Ticket ID,Customer Name,Customer Email,Customer Age,Customer Gender,Product Purchased,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Resolution,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating
0,1,Marisa Obrien,carrollallison@example.com,32,Other,GoPro Hero,22-03-2021,Technical issue,Product setup,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Social media,01-06-2023 12:15,NaN,NaN
1,2,Jessica Rios,clarkeashley@example.com,42,Female,LG Smart TV,22-05-2021,Technical issue,Peripheral compatibility,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Chat,01-06-2023 16:45,NaN,NaN
2,3,Christopher Robbins,gonzalestracy@example.com,48,Other,Dell XPS,14-07-2020,Technical issue,Network problem,I'm facing a problem with my {product_purchase...,Closed,Case maybe show recently my computer follow.,Low,Social media,01-06-2023 11:14,01-06-2023 18:05,3.0
3,4,Christina Dillon,bradleyolson@example.org,27,Female,Microsoft Office,13-11-2020,Billing inquiry,Account access,I'm having an issue with the {product_purchase...,Closed,Try capital clearly never color toward story.,Low,Social media,01-06-2023 07:29,01-06-2023 01:57,3.0
4,5,Alexander Carroll,bradleymark@example.com,67,Female,Autodesk AutoCAD,04-02-2020,Billing inquiry,Data loss,I'm having an issue with the {product_purchase...,Closed,West decision evidence bit.,Low,Email,01-06-2023 00:12,01-06-2023 19:53,1.0

In [5]:
#Displaying the Last  5 Rows
df.tail(5)

,Ticket ID,Customer Name,Customer Email,Customer Age,Customer Gender,Product Purchased,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Resolution,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating
994,995,Karen Anderson,jessethompson@example.org,61,Female,Nikon D,18-08-2021,Refund request,Product setup,I'm having an issue with the {product_purchase...,Open,NaN,High,Phone,NaN,NaN,NaN
995,996,Travis Ho,rcaldwell@example.org,36,Other,Samsung Soundbar,07-11-2020,Cancellation request,Product compatibility,The {product_purchased} is unable to establish...,Open,NaN,Critical,Chat,NaN,NaN,NaN
996,997,Kari Hale,jennifer89@example.net,57,Female,Samsung Soundbar,25-11-2021,Refund request,Software bug,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Medium,Social media,01-06-2023 02:15,NaN,NaN
997,998,Eric Harvey,julie04@example.net,43,Male,Apple AirPods,10-02-2021,Billing inquiry,Payment issue,I'm having an issue with the {product_purchase...,Closed,Grow laugh little air rest successful.,Medium,Phone,01-06-2023 04:09,01-06-2023 08:34,4.0
998,999,Thomas Wheeler,reedlacey@example.org,59,Other,Amazon Echo,03-03-2021,Cancellation request,Installation support,I've noticed a software bug in the {product_pu...,Pending Customer Response,NaN,Medium,Phone,01-06-2023 22:01,NaN,NaN

In [6]:
#Checking DataFrame Structural Summary
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 999 entries, 0 to 998
Data columns (total 17 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Ticket ID                     999 non-null    int64
 1   Customer Name                 999 non-null    str
 2   Customer Email                999 non-null    str
 3   Customer Age                  999 non-null    int64
 4   Customer Gender               999 non-null    str
 5   Product Purchased             999 non-null    str
 6   Date of Purchase              999 non-null    str
 7   Ticket Type                   999 non-null    str
 8   Ticket Subject                999 non-null    str
 9   Ticket Description            999 non-null    str
 10  Ticket Status                 999 non-null    str
 11  Resolution                    333 non-null    str
 12  Ticket Priority               999 non-null    str
 13  Ticket Channel                999 non-null    str
 14  First Response Time           668 non-null    str
 15  Time to Resolution            333 non-null    str
 16  Customer Satisfaction Rating  333 non-null    float64
dtypes: float64(1), int64(2), str(14)
memory usage: 132.8 KB

***Info:-*** Provides a complete summary of the dataset.It displays the number of rows and columns,column names,non-null value counts,and data type of each column,as well as the memory usage of the DataFrame.Therefore it helps to identify which columns need preprocessing.

In [7]:
#Checking Missing Values
df.isnull().sum()

Ticket ID                         0
Customer Name                     0
Customer Email                    0
Customer Age                      0
Customer Gender                   0
Product Purchased                 0
Date of Purchase                  0
Ticket Type                       0
Ticket Subject                    0
Ticket Description                0
Ticket Status                     0
Resolution                      666
Ticket Priority                   0
Ticket Channel                    0
First Response Time             331
Time to Resolution              666
Customer Satisfaction Rating    666
dtype: int64

In [8]:
#Displaying Statistical Summary
df.describe()

        Ticket ID  Customer Age  Customer Satisfaction Rating
count  999.000000    999.000000                    333.000000
mean   500.000000     43.920921                      2.957958
std    288.530761     15.075985                      1.413587
min      1.000000     18.000000                      1.000000
25%    250.500000     31.000000                      2.000000
50%    500.000000     44.000000                      3.000000
75%    749.500000     57.000000                      4.000000
max    999.000000     70.000000                      5.000000

In [9]:
df.dtypes

Ticket ID                         int64
Customer Name                       str
Customer Email                      str
Customer Age                      int64
Customer Gender                     str
Product Purchased                   str
Date of Purchase                    str
Ticket Type                         str
Ticket Subject                      str
Ticket Description                  str
Ticket Status                       str
Resolution                          str
Ticket Priority                     str
Ticket Channel                      str
First Response Time                 str
Time to Resolution                  str
Customer Satisfaction Rating    float64
dtype: object

<h2 style="
    text-align:center;
    background-color:#eef3ff;
    padding:10px 15px;
    border-radius:5px;
    color:#2c7be5;
    font-size:30px
">
 Data Preprocessing
</h2>

This step ensures the dataset is clean,consistent,and suitable for analysis.The cleaning steps include (i)**Correcting Data Types**,(ii)**Removing duplicates**,(iii)**Creating Derived columns**,(iv)**Standardizing column names and Categorical values**(v)****Handling missing values****(vi)**Removing unnecessary columns**,(vii)**Filtering data**.


### (1)Correcting column name into a unique format
Changing all column names into lower and replaced white spaces with _

In [10]:
#Standardizing Work Type Categories
df.columns=(
    df.columns.
    str.strip()
    .str.lower()
    .str.replace(" ","_")
)

In [11]:
df.columns

Index(['ticket_id', 'customer_name', 'customer_email', 'customer_age',
       'customer_gender', 'product_purchased', 'date_of_purchase',
       'ticket_type', 'ticket_subject', 'ticket_description', 'ticket_status',
       'resolution', 'ticket_priority', 'ticket_channel',
       'first_response_time', 'time_to_resolution',
       'customer_satisfaction_rating'],
      dtype='str')

In [12]:
df.dtypes

ticket_id                         int64
customer_name                       str
customer_email                      str
customer_age                      int64
customer_gender                     str
product_purchased                   str
date_of_purchase                    str
ticket_type                         str
ticket_subject                      str
ticket_description                  str
ticket_status                       str
resolution                          str
ticket_priority                     str
ticket_channel                      str
first_response_time                 str
time_to_resolution                  str
customer_satisfaction_rating    float64
dtype: object

### (2)Correcting Data Types
In this step,the data types of certain columns are corrected to ensure consistent and efficient analysis.This include fixing the **customer satisfaction rate ** to interger format column and updating **categorical** columns ,**Time of resolution, First response time , date of purchase** are corrected into date format ,and **gender** as categoricatl format

In [13]:
df["customer_satisfaction_rating"]=pd.to_numeric(df["customer_satisfaction_rating"].astype('Int64'))

In [38]:
df["time_to_resolution"]=pd.to_datetime(df["time_to_resolution"],errors="coerce")

In [36]:
df["first_response_time"]=pd.to_datetime(df["first_response_time"],errors="coerce")

In [37]:
df["date_of_purchase"]=pd.to_datetime(df["date_of_purchase"],errors="coerce")

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_9468\1760541882.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["date_of_purchase"]=pd.to_datetime(df["date_of_purchase"],errors="coerce")

In [39]:
df.dtypes

ticket_id                                int64
customer_name                              str
customer_email                             str
customer_age                             int64
customer_gender                            str
product_purchased                          str
date_of_purchase                datetime64[us]
ticket_type                                str
ticket_subject                             str
ticket_description                         str
ticket_status                              str
resolution                                 str
ticket_priority                            str
ticket_channel                             str
first_response_time             datetime64[us]
time_to_resolution              datetime64[us]
customer_satisfaction_rating             Int64
age_category                               str
ticket_priority_level                      str
dtype: object

### (3)Removing Duplicates
First, checking the number of rows which are duplicated and removing the duplicates

In [ ]:
#Checking the number of duplicate rows
print("Duplicate Rows Found:",df.duplicated().sum())

Duplicate Rows Found: 0

In [ ]:
#Removing duplicates
print("Number of Duplicate Rows:",df.drop_duplicates(inplace=True))

Number of Duplicate Rows: None

***Info:-*** The dataset was checked for duplicate entries using df.duplicated().sum().The result returned 0 duplicates,indicating that no repeated rows were found.The drop_duplicates() function was applied as a standard preprocessing step,although no removal was required.

### (4)Categorical Column
1)Making gender of the customer column as categorical format of "male','female',and other 
2)Making ticket type column into 4 catgories

In [ ]:
##Creating gender Category
gender_category = pd.CategoricalDtype(
    categories=["Male", "Female", "Other"],
    ordered=False
)

df["customer_gender"] = df["customer_gender"].astype(gender_category)

In [63]:
#Converting tikcet type  To Category
tikcet_category=["Billing inquiry","Technical issue","Cancellation request","Product inquiry","Refund request"]
df["ticket_type"]=df["ticket_type"].astype("category")

### (5)Handling Missing Values
The dataset contained **333** missing(NaN)values in the **resolution** column,**474** values in **first_response_time**,**5** in **customer_satisfaction_rating** and in.Since bmi is a numerical feature,these missing/Nan entries were replaced using the median,which is more robust to outliers and preserves the overall distribution.This ensures the dataset remains complete and suitable for further preprocessing.

In [64]:
df.isnull().sum()

ticket_id                       0
customer_name                   0
customer_email                  0
customer_age                    0
customer_gender                 0
product_purchased               0
date_of_purchase                0
ticket_type                     0
ticket_subject                  0
ticket_description              0
ticket_status                   0
resolution                      0
ticket_priority                 0
ticket_channel                  0
first_response_time             0
time_to_resolution              0
customer_satisfaction_rating    0
age_category                    0
ticket_priority_level           0
resolution_time                 0
ticket_type_category            0
dtype: int64

In [ ]:
df["resolution"].nunique()

333

In [ ]:
df["first_response_time"].nunique()

474

In [ ]:
df["customer_satisfaction_rating"].nunique()

5

In [ ]:
df["time_to_resolution"].nunique()

267

In [47]:
df["customer_satisfaction_rating"]=df["customer_satisfaction_rating"].fillna(df["customer_satisfaction_rating"].median())
df["time_to_resolution"]=df["time_to_resolution"].fillna(df["time_to_resolution"].ffill().bfill())
df["first_response_time"]=df["first_response_time"].fillna(df["first_response_time"].ffill().bfill())
df["resolution"] = df["resolution"].fillna(df["resolution"].mode()[0])

In [52]:
df.isnull().sum()

ticket_id                       0
customer_name                   0
customer_email                  0
customer_age                    0
customer_gender                 0
product_purchased               0
date_of_purchase                0
ticket_type                     0
ticket_subject                  0
ticket_description              0
ticket_status                   0
resolution                      0
ticket_priority                 0
ticket_channel                  0
first_response_time             0
time_to_resolution              0
customer_satisfaction_rating    0
age_category                    0
ticket_priority_level           0
resolution_time                 0
dtype: int64

### (6)Creating Derived Columns

In [73]:
#(1)Creating Age Group column
df["age_category"]=np.where(df["customer_age"]<=21,"Adult",np.where(df["customer_age"]<=45,"Middle Aged","Aged"))
df["age_category"]

0      Middle Aged
1      Middle Aged
2             Aged
3      Middle Aged
4             Aged
          ...
994           Aged
995    Middle Aged
996           Aged
997    Middle Aged
998           Aged
Name: age_category, Length: 999, dtype: str

***Info:-*** Created an **Age Group** categorical feature using where condition from 21 ols customer coming into the adult category, upto 45 as middle aged and remaining as aged

In [ ]:
#(2)creating ticket_priority_level
df["ticket_priority"].unique()
df["ticket_priority_level"]=np.where(df["ticket_priority"]=="Critical", "P1",np.where(df["ticket_priority"]=="Low", "P16",np.where(df["ticket_priority"]=="High","P4","P8")))
df["ticket_priority_level"]

0       P1
1       P1
2      P16
3      P16
4      P16
      ...
994     P4
995     P1
996     P8
997     P8
998     P8
Name: ticket_priority_level, Length: 999, dtype: str

***Info:-***  Categorized the ticket priorities to different priority levels, for critical priority  used P1 level ,for high P4 , for medium P8 and P16 for low priority tickets.

In [66]:
df.dtypes

ticket_id                                 int64
customer_name                               str
customer_email                              str
customer_age                              int64
customer_gender                             str
product_purchased                           str
date_of_purchase                 datetime64[us]
ticket_type                            category
ticket_subject                              str
ticket_status                               str
resolution                                  str
ticket_priority                             str
ticket_channel                              str
first_response_time              datetime64[us]
time_to_resolution               datetime64[us]
customer_satisfaction_rating              Int64
age_category                                str
ticket_priority_level                       str
resolution_time                 timedelta64[us]
ticket_type_category                        str
dtype: object

In [51]:
##(3)Creating Time taken
df["resolution_time"] = (
    df["time_to_resolution"] - df["first_response_time"]
)
df["resolution_time"]

df["resolution_time"].unique().tolist()

[Timedelta('0 days 05:50:00'),
 Timedelta('0 days 01:20:00'),
 Timedelta('0 days 06:51:00'),
 Timedelta('-1 days +18:28:00'),
 Timedelta('0 days 19:41:00'),
 Timedelta('0 days 09:21:00'),
 Timedelta('0 days 10:28:00'),
 Timedelta('0 days 02:07:00'),
 Timedelta('-1 days +21:22:00'),
 Timedelta('-1 days +14:24:00'),
 Timedelta('-1 days +12:53:00'),
 Timedelta('0 days 03:05:00'),
 Timedelta('-1 days +18:18:00'),
 Timedelta('-1 days +20:12:00'),
 Timedelta('-1 days +18:53:00'),
 Timedelta('0 days 19:43:00'),
 Timedelta('0 days 15:21:00'),
 Timedelta('0 days 11:23:00'),
 Timedelta('0 days 01:27:00'),
 Timedelta('0 days 00:27:00'),
 Timedelta('-1 days +10:01:00'),
 Timedelta('0 days 17:29:00'),
 Timedelta('0 days 00:34:00'),
 Timedelta('-1 days +11:40:00'),
 Timedelta('0 days 16:24:00'),
 Timedelta('-1 days +21:35:00'),
 Timedelta('-1 days +16:18:00'),
 Timedelta('-1 days +08:23:00'),
 Timedelta('-1 days +05:29:00'),
 Timedelta('-1 days +15:03:00'),
 Timedelta('-1 days +20:02:00'),
 Timedelta('-1 days +21:21:00'),
 Timedelta('0 days 05:41:00'),
 Timedelta('-1 days +22:43:00'),
 Timedelta('-1 days +18:10:00'),
 Timedelta('0 days 19:05:00'),
 Timedelta('0 days 09:46:00'),
 Timedelta('0 days 03:00:00'),
 Timedelta('-1 days +23:11:00'),
 Timedelta('-1 days +23:52:00'),
 Timedelta('-1 days +16:49:00'),
 Timedelta('-1 days +04:48:00'),
 Timedelta('0 days 11:37:00'),
 Timedelta('0 days 10:23:00'),
 Timedelta('0 days 11:09:00'),
 Timedelta('0 days 05:34:00'),
 Timedelta('0 days 05:11:00'),
 Timedelta('-1 days +13:13:00'),
 Timedelta('-1 days +22:20:00'),
 Timedelta('-1 days +22:42:00'),
 Timedelta('-1 days +04:53:00'),
 Timedelta('-1 days +11:47:00'),
 Timedelta('-1 days +20:05:00'),
 Timedelta('-1 days +22:24:00'),
 Timedelta('0 days 03:54:00'),
 Timedelta('0 days 07:54:00'),
 Timedelta('0 days 03:44:00'),
 Timedelta('0 days 14:55:00'),
 Timedelta('0 days 20:11:00'),
 Timedelta('-1 days +12:20:00'),
 Timedelta('-1 days +11:02:00'),
 Timedelta('-1 days +07:48:00'),
 Timedelta('-1 days +19:54:00'),
 Timedelta('0 days 02:55:00'),
 Timedelta('-1 days +11:12:00'),
 Timedelta('0 days 18:31:00'),
 Timedelta('0 days 16:44:00'),
 Timedelta('0 days 07:40:00'),
 Timedelta('-1 days +23:13:00'),
 Timedelta('-1 days +17:09:00'),
 Timedelta('-1 days +17:45:00'),
 Timedelta('0 days 12:16:00'),
 Timedelta('0 days 13:15:00'),
 Timedelta('0 days 09:08:00'),
 Timedelta('0 days 04:57:00'),
 Timedelta('0 days 05:20:00'),
 Timedelta('0 days 09:29:00'),
 Timedelta('0 days 09:19:00'),
 Timedelta('-1 days +19:37:00'),
 Timedelta('-1 days +23:15:00'),
 Timedelta('0 days 04:02:00'),
 Timedelta('0 days 10:27:00'),
 Timedelta('-1 days +20:47:00'),
 Timedelta('0 days 01:41:00'),
 Timedelta('0 days 12:35:00'),
 Timedelta('0 days 11:40:00'),
 Timedelta('-1 days +21:20:00'),
 Timedelta('-1 days +16:51:00'),
 Timedelta('-1 days +17:32:00'),
 Timedelta('-1 days +18:06:00'),
 Timedelta('-1 days +21:49:00'),
 Timedelta('-1 days +17:27:00'),
 Timedelta('-1 days +23:02:00'),
 Timedelta('-1 days +23:12:00'),
 Timedelta('-1 days +21:02:00'),
 Timedelta('-1 days +19:55:00'),
 Timedelta('-1 days +07:52:00'),
 Timedelta('-1 days +14:39:00'),
 Timedelta('-1 days +13:46:00'),
 Timedelta('-1 days +15:25:00'),
 Timedelta('0 days 05:10:00'),
 Timedelta('0 days 03:28:00'),
 Timedelta('-1 days +15:18:00'),
 Timedelta('-1 days +14:53:00'),
 Timedelta('0 days 04:01:00'),
 Timedelta('0 days 04:32:00'),
 Timedelta('-1 days +11:18:00'),
 Timedelta('-1 days +20:31:00'),
 Timedelta('0 days 12:39:00'),
 Timedelta('-1 days +12:59:00'),
 Timedelta('-1 days +13:47:00'),
 Timedelta('0 days 01:47:00'),
 Timedelta('0 days 14:05:00'),
 Timedelta('0 days 02:54:00'),
 Timedelta('-1 days +17:38:00'),
 Timedelta('-1 days +20:54:00'),
 Timedelta('0 days 07:43:00'),
 Timedelta('-1 days +23:14:00'),
 Timedelta('-1 days +18:09:00'),
 Timedelta('0 days 04:38:00'),
 Timedelta('-1 days +20:20:00'),
 Timedelta('-1 days +12:47:00'),
 Timedelta('0 days 03:50:00'),
 Timedelta('-1 days +10:36:00'),
 Timedelta('0 days 05:05:00'),
 Timedelta('0 days 02:22:00'),
 Timedelta('-1 days +14:04:00'),
 Timedelta('-1 days +20:21:00'),
 Timedelta('-1 days +10:37:00'),
 Timedelta('-1 days +15:34:00'),
 Timedelta('0 days 04:23:00'),
 Timedelta('0 days 02:24:00'),
 Timedelta('0 days 07:41:00'),
 Timedelta('0 days 08:55:00'),
 Timedelta('0 days 18:17:00'),
 Timedelta('0 days 07:55:00'),
 Timedelta('0 days 00:03:00'),
 Timedelta('0 days 07:33:00'),
 Timedelta('0 days 05:57:00'),
 Timedelta('0 days 16:59:00'),
 Timedelta('0 days 01:05:00'),
 Timedelta('-1 days +15:52:00'),
 Timedelta('-1 days +20:32:00'),
 Timedelta('-1 days +17:22:00'),
 Timedelta('0 days 03:48:00'),
 Timedelta('0 days 11:12:00'),
 Timedelta('0 days 02:30:00'),
 Timedelta('-1 days +18:23:00'),
 Timedelta('0 days 09:42:00'),
 Timedelta('-1 days +21:27:00'),
 Timedelta('0 days 04:53:00'),
 Timedelta('-1 days +16:22:00'),
 Timedelta('0 days 07:47:00'),
 Timedelta('-1 days +16:16:00'),
 Timedelta('-1 days +20:58:00'),
 Timedelta('0 days 13:39:00'),
 Timedelta('0 days 15:14:00'),
 Timedelta('0 days 15:42:00'),
 Timedelta('0 days 17:30:00'),
 Timedelta('0 days 16:08:00'),
 Timedelta('0 days 11:52:00'),
 Timedelta('-1 days +23:24:00'),
 Timedelta('0 days 04:49:00'),
 Timedelta('-1 days +17:10:00'),
 Timedelta('0 days 04:34:00'),
 Timedelta('-1 days +12:51:00'),
 Timedelta('-1 days +21:03:00'),
 Timedelta('0 days 05:55:00'),
 Timedelta('0 days 05:32:00'),
 Timedelta('0 days 11:17:00'),
 Timedelta('-1 days +18:24:00'),
 Timedelta('-1 days +12:03:00'),
 Timedelta('-1 days +19:57:00'),
 Timedelta('0 days 08:12:00'),
 Timedelta('0 days 08:48:00'),
 Timedelta('-1 days +23:21:00'),
 Timedelta('0 days 02:03:00'),
 Timedelta('-1 days +17:49:00'),
 Timedelta('0 days 13:43:00'),
 Timedelta('0 days 07:56:00'),
 Timedelta('0 days 03:09:00'),
 Timedelta('0 days 06:31:00'),
 Timedelta('-1 days +23:20:00'),
 Timedelta('0 days 04:18:00'),
 Timedelta('-1 days +22:26:00'),
 Timedelta('-1 days +20:59:00'),
 Timedelta('0 days 13:26:00'),
 Timedelta('0 days 14:45:00'),
 Timedelta('0 days 01:04:00'),
 Timedelta('0 days 08:56:00'),
 Timedelta('0 days 03:03:00'),
 Timedelta('0 days 11:59:00'),
 Timedelta('-1 days +14:58:00'),
 Timedelta('0 days 02:00:00'),
 Timedelta('0 days 01:16:00'),
 Timedelta('-1 days +23:43:00'),
 Timedelta('-1 days +22:09:00'),
 Timedelta('-1 days +10:50:00'),
 Timedelta('-1 days +22:23:00'),
 Timedelta('-1 days +22:36:00'),
 Timedelta('0 days 10:47:00'),
 Timedelta('0 days 06:30:00'),
 Timedelta('0 days 05:31:00'),
 Timedelta('0 days 09:54:00'),
 Timedelta('0 days 01:45:00'),
 Timedelta('0 days 09:17:00'),
 Timedelta('0 days 00:38:00'),
 Timedelta('0 days 07:58:00'),
 Timedelta('-1 days +19:22:00'),
 Timedelta('-1 days +13:36:00'),
 Timedelta('0 days 12:01:00'),
 Timedelta('-1 days +15:17:00'),
 Timedelta('-1 days +12:46:00'),
 Timedelta('-1 days +22:58:00'),
 Timedelta('0 days 15:43:00'),
 Timedelta('-1 days +18:32:00'),
 Timedelta('-1 days +09:35:00'),
 Timedelta('0 days 02:47:00'),
 Timedelta('0 days 19:37:00'),
 Timedelta('0 days 13:29:00'),
 Timedelta('0 days 02:20:00'),
 Timedelta('0 days 05:07:00'),
 Timedelta('-1 days +19:44:00'),
 Timedelta('-1 days +22:49:00'),
 Timedelta('0 days 05:52:00'),
 Timedelta('-1 days +17:06:00'),
 Timedelta('0 days 06:16:00'),
 Timedelta('0 days 00:50:00'),
 Timedelta('0 days 07:08:00'),
 Timedelta('0 days 00:21:00'),
 Timedelta('0 days 00:04:00'),
 Timedelta('0 days 01:40:00'),
 Timedelta('0 days 06:01:00'),
 Timedelta('0 days 11:13:00'),
 Timedelta('0 days 04:41:00'),
 Timedelta('-1 days +19:43:00'),
 Timedelta('-1 days +18:07:00'),
 Timedelta('0 days 01:11:00'),
 Timedelta('-1 days +21:51:00'),
 Timedelta('0 days 12:27:00'),
 Timedelta('0 days 12:19:00'),
 Timedelta('0 days 03:21:00'),
 Timedelta('0 days 01:56:00'),
 Timedelta('-1 days +19:49:00'),
 Timedelta('-1 days +16:13:00'),
 Timedelta('0 days 02:28:00'),
 Timedelta('0 days 02:17:00'),
 Timedelta('0 days 02:45:00'),
 Timedelta('0 days 04:44:00'),
 Timedelta('-1 days +22:28:00'),
 Timedelta('0 days 06:09:00'),
 Timedelta('0 days 04:26:00'),
 Timedelta('-1 days +09:45:00'),
 Timedelta('-1 days +07:01:00'),
 Timedelta('0 days 01:52:00'),
 Timedelta('0 days 19:14:00'),
 Timedelta('0 days 00:08:00'),
 Timedelta('0 days 08:33:00'),
 Timedelta('-1 days +23:44:00'),
 Timedelta('0 days 18:02:00'),
 Timedelta('-1 days +13:15:00'),
 Timedelta('0 days 01:17:00'),
 Timedelta('0 days 10:58:00'),
 Timedelta('0 days 03:43:00'),
 Timedelta('0 days 06:07:00'),
 Timedelta('-1 days +23:50:00'),
 Timedelta('-1 days +23:36:00'),
 Timedelta('0 days 03:45:00'),
 Timedelta('0 days 06:49:00'),
 Timedelta('-1 days +22:14:00'),
 Timedelta('-1 days +08:48:00'),
 Timedelta('-1 days +16:23:00'),
 Timedelta('-1 days +14:22:00'),
 Timedelta('-1 days +14:08:00'),
 Timedelta('-1 days +19:21:00'),
 Timedelta('0 days 04:27:00'),
 Timedelta('-1 days +14:10:00'),
 Timedelta('-1 days +23:31:00'),
 Timedelta('0 days 01:08:00'),
 Timedelta('-1 days +16:28:00'),
 Timedelta('0 days 02:31:00'),
 Timedelta('-1 days +11:37:00'),
 Timedelta('-1 days +17:52:00'),
 Timedelta('0 days 02:02:00'),
 Timedelta('-1 days +16:44:00'),
 Timedelta('-1 days +21:38:00'),
 Timedelta('-1 days +14:32:00'),
 Timedelta('-1 days +18:56:00'),
 Timedelta('-1 days +16:02:00'),
 Timedelta('-1 days +02:47:00'),
 Timedelta('-1 days +13:05:00'),
 Timedelta('0 days 11:45:00'),
 Timedelta('0 days 08:44:00'),
 Timedelta('-1 days +20:57:00'),
 Timedelta('-1 days +14:05:00'),
 Timedelta('0 days 15:22:00'),
 Timedelta('0 days 06:13:00'),
 Timedelta('0 days 08:31:00'),
 Timedelta('0 days 00:14:00'),
 Timedelta('0 days 03:26:00'),
 Timedelta('0 days 09:25:00'),
 Timedelta('0 days 13:38:00'),
 Timedelta('0 days 03:53:00'),
 Timedelta('0 days 07:14:00'),
 Timedelta('0 days 05:26:00'),
 Timedelta('-1 days +16:26:00'),
 Timedelta('-1 days +21:08:00'),
 Timedelta('0 days 11:22:00'),
 Timedelta('0 days 09:28:00'),
 Timedelta('0 days 07:00:00'),
 Timedelta('0 days 01:09:00'),
 Timedelta('-1 days +14:02:00'),
 Timedelta('-1 days +10:11:00'),
 Timedelta('0 days 18:46:00'),
 Timedelta('0 days 15:18:00'),
 Timedelta('0 days 16:22:00'),
 Timedelta('0 days 05:01:00'),
 Timedelta('-1 days +19:27:00'),
 Timedelta('0 days 04:04:00'),
 Timedelta('0 days 14:38:00'),
 Timedelta('0 days 10:26:00'),
 Timedelta('0 days 11:30:00'),
 Timedelta('0 days 00:32:00'),
 Timedelta('0 days 14:09:00'),
 Timedelta('0 days 17:40:00'),
 Timedelta('-1 days +15:19:00'),
 Timedelta('0 days 00:31:00'),
 Timedelta('-1 days +19:36:00'),
 Timedelta('-1 days +20:28:00'),
 Timedelta('-1 days +06:34:00'),
 Timedelta('-1 days +12:58:00'),
 Timedelta('0 days 12:12:00'),
 Timedelta('0 days 13:08:00'),
 Timedelta('0 days 11:32:00'),
 Timedelta('-1 days +19:06:00'),
 Timedelta('-1 days +13:54:00'),
 Timedelta('-1 days +06:12:00'),
 Timedelta('-1 days +06:03:00'),
 Timedelta('0 days 02:36:00'),
 Timedelta('-1 days +17:00:00'),
 Timedelta('-1 days +10:35:00'),
 Timedelta('-1 days +15:56:00'),
 Timedelta('-1 days +20:42:00'),
 Timedelta('-1 days +07:24:00'),
 Timedelta('-1 days +16:12:00'),
 Timedelta('-1 days +22:25:00'),
 Timedelta('0 days 13:47:00'),
 Timedelta('0 days 09:18:00'),
 Timedelta('0 days 08:17:00'),
 Timedelta('-1 days +21:28:00'),
 Timedelta('-1 days +18:43:00'),
 Timedelta('0 days 08:50:00'),
 Timedelta('-1 days +23:33:00'),
 Timedelta('-1 days +20:34:00'),
 Timedelta('0 days 09:10:00'),
 Timedelta('0 days 12:00:00'),
 Timedelta('0 days 09:16:00'),
 Timedelta('0 days 00:56:00'),
 Timedelta('-1 days +21:25:00'),
 Timedelta('-1 days +04:30:00'),
 Timedelta('0 days 00:11:00'),
 Timedelta('0 days 10:08:00'),
 Timedelta('0 days 08:21:00'),
 Timedelta('-1 days +22:12:00'),
 Timedelta('-1 days +10:56:00'),
 Timedelta('-1 days +21:17:00'),
 Timedelta('0 days 02:40:00'),
 Timedelta('-1 days +16:35:00'),
 Timedelta('0 days 01:19:00'),
 Timedelta('0 days 03:16:00'),
 Timedelta('0 days 10:40:00'),
 Timedelta('-1 days +15:53:00'),
 Timedelta('-1 days +08:55:00'),
 Timedelta('-1 days +07:03:00'),
 Timedelta('-1 days +07:44:00'),
 Timedelta('0 days 16:31:00'),
 Timedelta('0 days 10:25:00'),
 Timedelta('0 days 09:49:00'),
 Timedelta('0 days 12:07:00'),
 Timedelta('0 days 10:21:00'),
 Timedelta('0 days 00:10:00'),
 Timedelta('0 days 06:32:00'),
 Timedelta('0 days 14:56:00'),
 Timedelta('0 days 15:31:00'),
 Timedelta('-1 days +18:33:00'),
 Timedelta('-1 days +22:46:00'),
 Timedelta('-1 days +07:53:00'),
 Timedelta('-1 days +12:43:00'),
 Timedelta('-1 days +11:48:00'),
 Timedelta('-1 days +14:52:00'),
 Timedelta('-1 days +09:04:00'),
 Timedelta('0 days 13:14:00'),
 Timedelta('0 days 10:34:00'),
 Timedelta('0 days 06:46:00'),
 Timedelta('-1 days +11:26:00'),
 Timedelta('0 days 01:07:00'),
 Timedelta('-1 days +17:40:00'),
 Timedelta('-1 days +19:56:00'),
 Timedelta('-1 days +19:33:00'),
 Timedelta('-1 days +04:06:00'),
 Timedelta('0 days 03:12:00'),
 Timedelta('0 days 00:23:00'),
 Timedelta('-1 days +14:47:00'),
 Timedelta('-1 days +13:59:00'),
 Timedelta('-1 days +06:53:00'),
 Timedelta('-1 days +22:31:00'),
 Timedelta('0 days 11:55:00'),
 Timedelta('0 days 20:17:00'),
 Timedelta('-1 days +22:48:00'),
 Timedelta('-1 days +02:38:00'),
 Timedelta('-1 days +21:59:00'),
 Timedelta('0 days 16:20:00'),
 Timedelta('0 days 08:01:00'),
 Timedelta('-1 days +13:37:00'),
 Timedelta('-1 days +16:21:00'),
 Timedelta('0 days 02:01:00'),
 Timedelta('-1 days +21:16:00'),
 Timedelta('-1 days +22:15:00'),
 Timedelta('-1 days +17:35:00'),
 Timedelta('-1 days +15:32:00'),
 Timedelta('0 days 07:30:00'),
 Timedelta('0 days 02:15:00'),
 Timedelta('0 days 03:56:00'),
 Timedelta('0 days 01:55:00'),
 Timedelta('-1 days +12:19:00'),
 Timedelta('-1 days +19:25:00'),
 Timedelta('0 days 17:55:00'),
 Timedelta('-1 days +09:24:00'),
 Timedelta('0 days 09:45:00'),
 Timedelta('0 days 09:44:00'),
 Timedelta('-1 days +19:58:00'),
 Timedelta('0 days 04:51:00'),
 Timedelta('0 days 12:34:00'),
 Timedelta('-1 days +20:25:00'),
 Timedelta('0 days 07:50:00'),
 Timedelta('0 days 00:09:00'),
 Timedelta('-1 days +14:31:00'),
 Timedelta('0 days 10:22:00'),
 Timedelta('0 days 05:43:00'),
 Timedelta('0 days 06:33:00'),
 Timedelta('0 days 16:34:00'),
 Timedelta('0 days 14:58:00'),
 Timedelta('0 days 07:37:00'),
 Timedelta('0 days 03:10:00'),
 Timedelta('0 days 15:34:00'),
 Timedelta('0 days 00:18:00'),
 Timedelta('0 days 04:21:00'),
 Timedelta('0 days 13:11:00'),
 Timedelta('0 days 00:49:00'),
 Timedelta('0 days 02:29:00'),
 Timedelta('-1 days +19:45:00'),
 Timedelta('0 days 03:36:00'),
 Timedelta('-1 days +20:35:00'),
 Timedelta('-1 days +23:42:00'),
 Timedelta('0 days 15:32:00'),
 Timedelta('0 days 06:35:00'),
 Timedelta('0 days 16:54:00'),
 Timedelta('0 days 21:08:00'),
 Timedelta('0 days 00:17:00'),
 Timedelta('0 days 15:54:00'),
 Timedelta('0 days 14:22:00'),
 Timedelta('-1 days +21:47:00'),
 Timedelta('-1 days +07:04:00'),
 Timedelta('-1 days +05:36:00'),
 Timedelta('-1 days +13:02:00'),
 Timedelta('-1 days +14:20:00'),
 Timedelta('-1 days +15:48:00'),
 Timedelta('-1 days +18:02:00'),
 Timedelta('0 days 00:51:00'),
 Timedelta('0 days 06:15:00'),
 Timedelta('0 days 11:19:00'),
 Timedelta('-1 days +13:19:00'),
 Timedelta('-1 days +09:01:00'),
 Timedelta('0 days 02:32:00'),
 Timedelta('0 days 03:14:00'),
 Timedelta('0 days 03:35:00'),
 Timedelta('-1 days +06:41:00'),
 Timedelta('-1 days +21:40:00'),
 Timedelta('-1 days +16:24:00'),
 Timedelta('0 days 04:30:00'),
 Timedelta('-1 days +20:17:00'),
 Timedelta('0 days 08:53:00'),
 Timedelta('0 days 11:20:00'),
 Timedelta('-1 days +06:23:00'),
 Timedelta('0 days 12:11:00'),
 Timedelta('0 days 03:47:00'),
 Timedelta('-1 days +07:56:00'),
 Timedelta('-1 days +12:36:00'),
 Timedelta('-1 days +19:42:00'),
 Timedelta('-1 days +16:29:00'),
 Timedelta('-1 days +06:49:00'),
 Timedelta('0 days 04:07:00'),
 Timedelta('0 days 12:33:00'),
 Timedelta('0 days 04:46:00'),
 Timedelta('0 days 11:48:00'),
 Timedelta('0 days 01:44:00'),
 Timedelta('-1 days +16:37:00'),
 Timedelta('-1 days +15:21:00'),
 Timedelta('0 days 13:50:00'),
 Timedelta('0 days 02:56:00'),
 Timedelta('0 days 12:50:00'),
 Timedelta('0 days 01:26:00'),
 Timedelta('0 days 06:57:00'),
 Timedelta('0 days 12:25:00'),
 Timedelta('0 days 04:09:00'),
 Timedelta('-1 days +21:14:00'),
 Timedelta('-1 days +12:16:00'),
 Timedelta('0 days 03:42:00'),
 Timedelta('0 days 09:43:00'),
 Timedelta('-1 days +10:24:00'),
 Timedelta('-1 days +08:43:00'),
 Timedelta('-1 days +14:26:00'),
 Timedelta('0 days 08:14:00'),
 Timedelta('0 days 09:05:00'),
 Timedelta('0 days 15:46:00'),
 Timedelta('0 days 12:23:00'),
 Timedelta('0 days 01:14:00'),
 Timedelta('-1 days +20:56:00'),
 Timedelta('0 days 10:43:00'),
 Timedelta('-1 days +13:30:00'),
 Timedelta('-1 days +05:34:00'),
 Timedelta('-1 days +10:05:00'),
 Timedelta('0 days 03:25:00'),
 Timedelta('0 days 00:28:00'),
 Timedelta('0 days 04:37:00'),
 Timedelta('0 days 07:28:00'),
 Timedelta('-1 days +15:08:00'),
 Timedelta('-1 days +13:06:00'),
 Timedelta('0 days 03:08:00'),
 Timedelta('0 days 04:42:00'),
 Timedelta('0 days 14:50:00'),
 Timedelta('0 days 07:45:00'),
 Timedelta('0 days 07:27:00'),
 Timedelta('0 days 18:24:00'),
 Timedelta('0 days 08:32:00'),
 Timedelta('0 days 13:02:00'),
 Timedelta('-1 days +15:23:00'),
 Timedelta('0 days 01:58:00'),
 Timedelta('-1 days +11:19:00'),
 Timedelta('-1 days +14:41:00'),
 Timedelta('-1 days +20:08:00'),
 Timedelta('-1 days +21:01:00'),
 Timedelta('0 days 02:44:00'),
 Timedelta('0 days 00:55:00'),
 Timedelta('0 days 04:25:00'),
 Timedelta('-1 days +10:33:00')]

##(4)Ticket Type Category
To categorise the ticket type using the ticket type category 
for Billing related categorised to Account
Technical issue  to IT 
Refund request issue Payment 
Cancellation request to Cancelled 
Product Inquiry to Product related

In [61]:
## Creating ticket_type_category
df["ticket_type_category"]=np.where(df["ticket_type"]=="Technical issue","IT",
                                    np.where(df["ticket_type"]=="Billing inquiry","Account",
                                             np.where(df["ticket_type"]=="Refund request","Payment",
                                                      np.where(df["ticket_type"]=="Cancellation request",
                                                               "Cancelled","Product "))))
df["ticket_type_category"]

0             IT
1             IT
2             IT
3        Account
4        Account
         ...
994      Payment
995    Cancelled
996      Payment
997      Account
998    Cancelled
Name: ticket_type_category, Length: 999, dtype: str

### (7)Removing Un-necessary Columns
The **Ticket_description** column was removed because it serves only as a **ticket description** and does not contribute to analysis,EDA,or visualization.Eliminating such non-informative fields helps simplify the dataset and ensures that only meaningful features are used in further analytical steps.

In [65]:
#Removing the Id Column
df=df.drop(columns=["ticket_description"])

### (8)Filtering Data
Filtering is the process of removing rows that are incorrect,irrelevant,or not useful for analysis.This step ensures the dataset only contains meaningful and valid observations.

In [67]:
#Displaying the frequency of each gender category
df["customer_gender"].value_counts()

customer_gender
Female    360
Other     327
Male      312
Name: count, dtype: int64

In [74]:
#Frequency Distribution of Age Group
df["age_category"].value_counts()

age_category
Aged           477
Middle Aged    441
Adult           81
Name: count, dtype: int64

In [75]:
#Displaying Min and Max Values of Age
print("Minimum Age:",df["customer_age"].min())
print("Maximum Age:",df["customer_age"].max())

Minimum Age: 18
Maximum Age: 70

In [76]:
df.columns

Index(['ticket_id', 'customer_name', 'customer_email', 'customer_age',
       'customer_gender', 'product_purchased', 'date_of_purchase',
       'ticket_type', 'ticket_subject', 'ticket_status', 'resolution',
       'ticket_priority', 'ticket_channel', 'first_response_time',
       'time_to_resolution', 'customer_satisfaction_rating', 'age_category',
       'ticket_priority_level', 'resolution_time', 'ticket_type_category'],
      dtype='str')

In [78]:
df["ticket_priority_level"].value_counts()

ticket_priority_level
P1     279
P8     258
P16    253
P4     209
Name: count, dtype: int64

### (9) Final

In [79]:
#Displaying Dimensions of the dataset
print("Number of Rows:",df.shape[0])
print("Number of Columns:",df.shape[1])

Number of Rows: 999
Number of Columns: 20

***Info:-*** Updated Rows and Columns of the dataset/table,where 1000 rows are reduced by 999 rows and 15 columns are increased to 20 columns.

<div style=" margin-top:15px;background:#e7f9ed;padding:12px 16px;border-left:5px solid #2ecc71;border-radius:6px;font-family:Arial,sans-serif;font-weight:bold;color:#0d6b2d;">✔ Data Preprocessing  successfully completed !!  Ensuring the dataset is clean,consistent,and ready for analysis.</div>

<h2 style="
    text-align:center;
    background-color:#eef3ff;
    padding:10px 15px;
    border-radius:5px;
    color:#2c7be5;
    font-size:30px
">
 Exploratory Data Analysis (EDA)
</h2>

**Exploratory Data Analysis (EDA)** is the process of summarizing,visualizing,and understanding the underlying patterns,trends,relationships,and distributions within the dataset before modeling or decision making.

#### (i) Overview of the Dataset
Examine the dataset's size,data types using **df.shape**,**df.head()**,and **df.info()** to get an initial understanding of the data.

In [80]:
#Displaying the Dimensions of the Dataset
print("Number of Rows:",df.shape[0])
print("Number of Columns:",df.shape[1])

Number of Rows: 999
Number of Columns: 20

In [81]:
#Checking Dataframe Structural Summary
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 999 entries, 0 to 998
Data columns (total 20 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   ticket_id                     999 non-null    int64
 1   customer_name                 999 non-null    str
 2   customer_email                999 non-null    str
 3   customer_age                  999 non-null    int64
 4   customer_gender               999 non-null    str
 5   product_purchased             999 non-null    str
 6   date_of_purchase              999 non-null    datetime64[us]
 7   ticket_type                   999 non-null    category
 8   ticket_subject                999 non-null    str
 9   ticket_status                 999 non-null    str
 10  resolution                    999 non-null    str
 11  ticket_priority               999 non-null    str
 12  ticket_channel                999 non-null    str
 13  first_response_time           999 non-null    datetime64[us]
 14  time_to_resolution            999 non-null    datetime64[us]
 15  customer_satisfaction_rating  999 non-null    Int64
 16  age_category                  999 non-null    str
 17  ticket_priority_level         999 non-null    str
 18  resolution_time               999 non-null    timedelta64[us]
 19  ticket_type_category          999 non-null    str
dtypes: Int64(1), category(1), datetime64[us](3), int64(2), str(12), timedelta64[us](1)
memory usage: 150.4 KB

In [82]:
#Displaying the First 5 Rows
df.head()

,ticket_id,customer_name,customer_email,customer_age,customer_gender,product_purchased,date_of_purchase,ticket_type,ticket_subject,ticket_status,resolution,ticket_priority,ticket_channel,first_response_time,time_to_resolution,customer_satisfaction_rating,age_category,ticket_priority_level,resolution_time,ticket_type_category
0,1,Marisa Obrien,carrollallison@example.com,32,Other,GoPro Hero,2021-03-22,Technical issue,Product setup,Pending Customer Response,Ability though ability recently drive order th...,Critical,Social media,2023-01-06 12:15:00,2023-01-06 18:05:00,3,Middle Aged,P1,0 days 05:50:00,IT
1,2,Jessica Rios,clarkeashley@example.com,42,Female,LG Smart TV,2021-05-22,Technical issue,Peripheral compatibility,Pending Customer Response,Ability though ability recently drive order th...,Critical,Chat,2023-01-06 16:45:00,2023-01-06 18:05:00,3,Middle Aged,P1,0 days 01:20:00,IT
2,3,Christopher Robbins,gonzalestracy@example.com,48,Other,Dell XPS,2020-07-14,Technical issue,Network problem,Closed,Case maybe show recently my computer follow.,Low,Social media,2023-01-06 11:14:00,2023-01-06 18:05:00,3,Aged,P16,0 days 06:51:00,IT
3,4,Christina Dillon,bradleyolson@example.org,27,Female,Microsoft Office,2020-11-13,Billing inquiry,Account access,Closed,Try capital clearly never color toward story.,Low,Social media,2023-01-06 07:29:00,2023-01-06 01:57:00,3,Middle Aged,P16,-1 days +18:28:00,Account
4,5,Alexander Carroll,bradleymark@example.com,67,Female,Autodesk AutoCAD,2020-02-04,Billing inquiry,Data loss,Closed,West decision evidence bit.,Low,Email,2023-01-06 00:12:00,2023-01-06 19:53:00,1,Aged,P16,0 days 19:41:00,Account

#### (ii) Univariate Analysis
It examines each feature individually to understand its basic distribution and key statistical properties.

In [83]:
#Displaying Statistical Summary
df.describe()

,ticket_id,customer_age,date_of_purchase,first_response_time,time_to_resolution,customer_satisfaction_rating,resolution_time
count,999.000000,999.000000,999,999,999,999.0,999
mean,500.000000,43.920921,2021-01-04 11:11:42.702702,2023-01-06 10:25:04.204204,2023-01-06 11:41:40.720720,2.985986,0 days 01:16:36.516516
min,1.000000,18.000000,2020-01-02 00:00:00,2023-01-06 00:00:00,2023-01-06 00:04:00,1.0,-1 days +02:38:00
25%,250.500000,31.000000,2020-07-13 00:00:00,2023-01-06 04:20:30,2023-01-06 06:25:00,3.0,-1 days +18:53:00
50%,500.000000,44.000000,2021-01-15 00:00:00,2023-01-06 10:23:00,2023-01-06 12:14:00,3.0,0 days 01:52:00
75%,749.500000,57.000000,2021-06-26 12:00:00,2023-01-06 16:17:00,2023-01-06 17:04:00,3.0,0 days 07:55:00
max,999.000000,70.000000,2021-12-29 00:00:00,2023-01-06 22:01:00,2023-01-06 21:50:00,5.0,0 days 21:08:00
std,288.530761,15.075985,NaN,NaN,NaN,0.815558,0 days 09:11:55.620406

#### Frequency Distribution(Categorical Columns)
It involves examining all **categorical columns** to understand the different categories they contain and how **frequently** each category appears in the dataset.It helps identify dominant groups,rare categories,and any imbalance in the data.

In [84]:
for col in df.select_dtypes(include="category"):
    print("\nColumn:",col)
    print(df[col].value_counts())

Column: ticket_type
ticket_type
Cancellation request    220
Technical issue         215
Refund request          196
Billing inquiry         184
Product inquiry         184
Name: count, dtype: int64

#### (iii) Bivariate Analysis
It examines the relationship between two variables to identify patterns,associations,and differences.It helps understand how one feature may influence or vary with another.

Examining the average of customer satisfaction rate with ticket type

In [86]:
df.groupby("ticket_type")["customer_satisfaction_rating"].mean()

ticket_type
Billing inquiry         3.097826
Cancellation request    3.009091
Product inquiry         2.978261
Refund request          2.913265
Technical issue         2.939535
Name: customer_satisfaction_rating, dtype: Float64

In [87]:
df.columns

Index(['ticket_id', 'customer_name', 'customer_email', 'customer_age',
       'customer_gender', 'product_purchased', 'date_of_purchase',
       'ticket_type', 'ticket_subject', 'ticket_status', 'resolution',
       'ticket_priority', 'ticket_channel', 'first_response_time',
       'time_to_resolution', 'customer_satisfaction_rating', 'age_category',
       'ticket_priority_level', 'resolution_time', 'ticket_type_category'],
      dtype='str')

Examining the average of resolution time with ticket type

In [89]:
df.groupby("ticket_type")["resolution_time"].median()

ticket_type
Billing inquiry        0 days 00:27:30
Cancellation request   0 days 02:00:00
Product inquiry        0 days 01:42:30
Refund request         0 days 02:26:00
Technical issue        0 days 02:02:00
Name: resolution_time, dtype: timedelta64[us]

Examining the average pf customer satisfaction rate with ticket priority level

In [90]:
df.groupby("ticket_priority_level")["customer_satisfaction_rating"].mean()

ticket_priority_level
P1     2.978495
P16    3.027668
P4     2.980861
P8     2.957364
Name: customer_satisfaction_rating, dtype: Float64

#### (iv) Multivariate Analysis
It examines how multiple variables interact simultaneously to uncover deeper patterns,combined effects,and factors influencing the target outcome.

In [91]:
df.columns

Index(['ticket_id', 'customer_name', 'customer_email', 'customer_age',
       'customer_gender', 'product_purchased', 'date_of_purchase',
       'ticket_type', 'ticket_subject', 'ticket_status', 'resolution',
       'ticket_priority', 'ticket_channel', 'first_response_time',
       'time_to_resolution', 'customer_satisfaction_rating', 'age_category',
       'ticket_priority_level', 'resolution_time', 'ticket_type_category'],
      dtype='str')

In [94]:
df.groupby("ticket_type").agg(
    {
        "resolution_time":"mean",
        "ticket_priority_level":"max",
        "customer_age":"min"


    }
)

,resolution_time,ticket_priority_level,customer_age
ticket_type,,,
Billing inquiry,0 days 00:08:01.304347,P8,18
Cancellation request,0 days 01:37:23.454545,P8,18
Product inquiry,0 days 01:05:02.282608,P8,18
Refund request,0 days 01:54:19.285714,P8,18
Technical issue,0 days 01:29:33.767441,P8,18

In [97]:
df.groupby("ticket_priority_level").agg(
    {
        "resolution_time":"mean",
        "ticket_priority_level":"min",
        "customer_satisfaction_rating":"max"


    }
)

,resolution_time,ticket_priority_level,customer_satisfaction_rating
ticket_priority_level,,,
P1,0 days 01:02:25.806451,P1,5
P16,0 days 01:06:20.158102,P16,5
P4,0 days 02:20:31.291866,P4,5
P8,0 days 00:50:14.418604,P8,5

In [98]:
df.groupby("ticket_channel").agg(
    {
        "resolution_time":"mean",
        "ticket_priority_level":"max",
        "first_response_time":"min",
        "time_to_resolution":"max",
        "resolution_time":"sum"

    }
)

,resolution_time,ticket_priority_level,first_response_time,time_to_resolution
ticket_channel,,,,
Chat,6 days 23:33:00,P8,2023-01-06 00:05:00,2023-01-06 21:49:00
Email,10 days 11:04:00,P8,2023-01-06 00:00:00,2023-01-06 21:46:00
Phone,12 days 18:29:00,P8,2023-01-06 00:00:00,2023-01-06 21:50:00
Social media,22 days 22:26:00,P8,2023-01-06 00:00:00,2023-01-06 21:50:00